### 1. What is a Python library? Why do we use Python libraries?

In [1]:
import numpy # here numpy is a python library.
# there are many libraries which are used to mor̥e efficient of the code.

### 2. What is the difference between Numpy array and List?

In [4]:
import numpy as np # import numpy.
arr=np.array([1,2,3,4,5]) # numpy array is a faster than list which is used to store homogenious data. 
arr # that means numpy array strings have only contain strings.

array([1, 2, 3, 4, 5])

In [5]:
a=[1,2,3,4,5]
a # list is used to store heteroginious data that means list contains any datatypes. 

[1, 2, 3, 4, 5]

### 3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [11]:
import numpy as np
arr=np.array([[1, 2, 3, 4],
             [5, 6, 7, 8],
             [9, 10, 11, 12]])
arr.shape # shape of a array.

(3, 4)

In [12]:
arr.size # size of a array.

12

In [13]:
arr.ndim # dimension of a array.

2

### 4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [19]:
import numpy as np
arr=np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
arr1=arr[0,:] # slicing.
arr1 # print the result.

array([1, 2, 3, 4])

### 5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [38]:
import numpy as np
arr=np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
arr1=arr[2,3]
arr1 # access the third row and fourth column element.

12

### 6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [40]:
import numpy as np
arr=np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
arr1=arr[arr%2!=0]
arr1 # print the odd elements in a numpy array.

array([ 1,  3,  5,  7,  9, 11])

### 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [54]:
import numpy as np
arr=np.random.random((3,3))
arr # print the 3*3 matrix.

array([[0.69294635, 0.18122879, 0.27460814],
       [0.40566075, 0.35894306, 0.62622257],
       [0.02387265, 0.67270418, 0.04862138]])

### 8. Describe the difference between np.random.rand and np.random.ran^n?

In [55]:
import numpy as np
arr=np.random.rand(2,3)
arr # print tyhe result.

array([[0.86596227, 0.40875591, 0.69352571],
       [0.6226435 , 0.43161869, 0.3223361 ]])

In [56]:
import numpy as np
arr1=np.random.randn(2,3)
arr1 # print the result.

array([[-1.0619633 ,  0.00165667, -0.0803121 ],
       [ 0.21203332, -0.26395218, -0.20758173]])

### 9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [58]:
import numpy as np
arr=np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
arr1=np.expand_dims(arr,axis=1)
arr1 # print the rewsult.

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

### 10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [63]:
import numpy as np
arr=np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
arr1=arr.T
arr1 # print the result.

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

### 11. Consider the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

In [5]:
import numpy as np
arr=np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

arr1=np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

# 1.Index wise multiplication:
arr*arr1

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [8]:
# 2.Matix multiplication:
import numpy as np

# Define two matrices
matrix1 = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

matrix2 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9],
                    [10, 11, 12]])

# Perform matrix multiplication using np.dot()
result_dot = np.dot(matrix1, matrix2)
# Perform matrix multiplication using @ operator (Python 3.5+)
result_at_operator = matrix1 @ matrix2
print("Matrix multiplication using np.dot():")
print(result_dot)
print("\nMatrix multiplication using @ operator:")
print(result_at_operator)

Matrix multiplication using np.dot():
[[ 70  80  90]
 [158 184 210]
 [246 288 330]]

Matrix multiplication using @ operator:
[[ 70  80  90]
 [158 184 210]
 [246 288 330]]


In [9]:
# 3. Add both the matics:
import numpy as np
arr=np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

arr1=np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
arr+arr1

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [10]:
# 4.subtact matix B from A:
import numpy as np
arr=np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

arr1=np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
arr1-arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
# 5.Divide Matix B by A:
import numpy as np
arr=np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

arr1=np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
arr1/arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### 12. Which function in Numpy can be used to swap the byte order of an array?

In [15]:
import numpy as np
res=np.array([1,2,3,4],dtype=np.int32)
result=res.byteswap()
print(f"array:{res}")
print(f"swapped array:{result}")

array:[1 2 3 4]
swapped array:[16777216 33554432 50331648 67108864]


### 13. What is the significance of the np.linalg.inv function?

In [16]:
import numpy as np
a=np.array([[1,2],
            [3,4]])
a_inv=np.linalg.inv(a)
print(a)
print(a_inv) # print the ressult of a inverese of a matrix.

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


### 14. What does the np.reshape function do, and how is it used?

In [19]:
import numpy as np
arr=np.arange(6)
res=np.reshape(arr,(2,3))
res

array([[0, 1, 2],
       [3, 4, 5]])

### 15. What is broadcasting in Numpy?

In [22]:
import numpy as np
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
arr1=np.array([10,20,30])
res=arr+arr1
res

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])